spring.application.name=devops-test
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/devops_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=INFO
logging.level.pl.slsolutions=DEBUG

